<?php

namespace App\Http\Requests\Dealer;

use Illuminate\Foundation\Http\FormRequest;

/**
 * @OA\Schema(
 *     schema="UpdateVehicleRequest",
 *     type="object",
 *     title="Update Vehicle Request",
 *     description="Request body for updating a vehicle",
 *     required={"vehicle_type", "cmp_id", "model_id"},
 *     @OA\Property(property="vehicle_type", type="integer", enum={1,2}, example=1, description="1=Car, 2=Bike"),
 *     @OA\Property(property="cmp_id", type="integer", example=1),
 *     @OA\Property(property="model_id", type="integer", example=10),
 *     @OA\Property(property="variant_id", type="integer", example=3),
 *     @OA\Property(property="fuel_type", type="integer", example=2),
 *     @OA\Property(property="mileage", type="number", format="float", example=18.5),
 *     @OA\Property(property="kms_driven", type="integer", example=24000),
 *     @OA\Property(property="manufacture_year", type="integer", example=2021),
 *     @OA\Property(property="registration_year", type="integer", example=2022),
 *     @OA\Property(property="color_id", type="integer", example=4),
 *     @OA\Property(property="regular_price", type="number", format="float", example=950000),
 *     @OA\Property(property="selling_price", type="number", format="float", example=920000),
 *     @OA\Property(property="is_active", type="integer", enum={1,2,3,4}),
 *     @OA\Property(property="onsale_status", type="integer", enum={1,2}),
 *     @OA\Property(property="onsale_percentage", type="number", format="float", example=10.5),
 *     @OA\Property(property="search_keywords", type="string", example="SUV, black, 2020"),
 *     @OA\Property(property="insurance_type", type="integer", enum={1,2}),
 *     @OA\Property(property="insurance_validity", type="string", format="date"),
 *     @OA\Property(property="accidental_status", type="integer", enum={1,2}),
 *     @OA\Property(property="flooded_status", type="integer", enum={1,2}),
 *     @OA\Property(property="last_service_kms", type="integer"),
 *     @OA\Property(property="last_service_date", type="string", format="date"),
 *     @OA\Property(property="reservation_amt", type="integer"),
 *     @OA\Property(property="pricing_type", type="integer", enum={1,2}),
 *     @OA\Property(property="emi_option", type="integer", enum={1,2}),
 *     @OA\Property(property="avg_interest_rate", type="number", format="float"),
 *     @OA\Property(property="tenure_months", type="integer"),
 *     @OA\Property(property="soldReason", type="string"),
 *     @OA\Property(property="is_admin_approved", type="string", enum={"0","1"}),
 *     @OA\Property(property="updated_by", type="integer"),
 *     @OA\Property(property="thumbnail_url", type="string", format="binary"),
 *     @OA\Property(property="branch_id", type="integer"),
 *     @OA\Property(property="rto", type="string"),
 *     @OA\Property(property="registered_state_id", type="integer"),
 *     @OA\Property(property="owner", type="integer"),
 *
 *     @OA\Property(property="transmission_id", type="integer"),
 *     @OA\Property(property="body_type", type="integer"),
 *     @OA\Property(property="car_no_of_airbags", type="integer"),
 *     @OA\Property(property="car_central_locking", type="integer", enum={1,2,3}),
 *     @OA\Property(property="car_seat_upholstery", type="integer", enum={1,2}),
 *     @OA\Property(property="car_sunroof", type="integer", enum={1,2}),
 *     @OA\Property(property="car_integrated_music_system", type="integer", enum={1,2}),
 *     @OA\Property(property="car_rear_ac", type="integer", enum={1,2}),
 *     @OA\Property(property="car_outside_rear_view_mirrors", type="integer", enum={1,2}),
 *     @OA\Property(property="car_power_windows", type="integer", enum={1,2}),
 *     @OA\Property(property="car_engine_start_stop", type="integer", enum={1,2}),
 *     @OA\Property(property="car_headlamps", type="integer", enum={1,2}),
 *     @OA\Property(property="car_power_steering", type="integer", enum={1,2}),
 *
 *     @OA\Property(property="bike_headlight_type", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_odometer", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_drl", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_mobile_connectivity", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_gps_navigation", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_usb_charging_port", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_low_battery_indicator", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_under_seat_storage", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_speedometer", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_stand_alarm", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_low_fuel_indicator", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_low_oil_indicator", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_start_type", type="integer", enum={1,2,3}),
 *     @OA\Property(property="bike_kill_switch", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_break_light", type="integer", enum={1,2}),
 *     @OA\Property(property="bike_turn_signal_indicator", type="integer", enum={1,2})
 * )
 */
class UpdateVehicleRequest extends FormRequest {
    public function authorize() {
        return true;
    }

    public function rules() {
        return [
            'vehicle_type' => 'nullable|integer|in:1,2',
            'cmp_id' => 'nullable|integer',
            'model_id' => 'nullable|integer',
            'variant_id' => 'nullable|integer',
            'fuel_type' => 'nullable|integer',
            'mileage' => 'nullable|numeric',
            'kms_driven' => 'nullable|integer',
            'manufacture_year' => 'nullable|integer',
            'registration_year' => 'nullable|integer',
            'color_id' => 'nullable|integer',
            'regular_price' => 'nullable|numeric',
            'selling_price' => 'nullable|numeric',
            'is_active' => 'nullable|integer|in:1,2,3,4',
            'onsale_status' => 'nullable|integer|in:1,2',
            'onsale_percentage' => 'nullable|numeric',
            'search_keywords' => 'nullable|string',
            'insurance_type' => 'nullable|integer|in:1,2',
            'insurance_validity' => 'nullable|date',
            'accidental_status' => 'nullable|integer|in:1,2',
            'flooded_status' => 'nullable|integer|in:1,2',
            'last_service_kms' => 'nullable|integer',
            'last_service_date' => 'nullable|date',
            'reservation_amt' => 'nullable|integer',
            'pricing_type' => 'nullable|integer|in:1,2',
            'emi_option' => 'nullable|integer|in:1,2',
            'avg_interest_rate' => 'nullable|numeric',
            'tenure_months' => 'nullable|integer',
            'soldReason' => 'nullable|string',
            'is_admin_approved' => 'nullable|in:0,1',
            'updated_by' => 'nullable|integer',
            'thumbnail_url' => 'nullable|file|mimes:jpg,jpeg,png|max:2048',
            'branch_id' => 'nullable|integer',
            'rto' => 'nullable|string',
            'registered_state_id' => 'nullable|integer',
            'owner' => 'nullable|integer',

            // Car-specific
            'transmission_id' => 'nullable|integer',
            'body_type' => 'nullable|integer',
            'car_no_of_airbags' => 'nullable|integer',
            'car_central_locking' => 'nullable|integer|in:1,2,3',
            'car_seat_upholstery' => 'nullable|integer|in:1,2',
            'car_sunroof' => 'nullable|integer|in:1,2',
            'car_integrated_music_system' => 'nullable|integer|in:1,2',
            'car_rear_ac' => 'nullable|integer|in:1,2',
            'car_outside_rear_view_mirrors' => 'nullable|integer|in:1,2',
            'car_power_windows' => 'nullable|integer|in:1,2',
            'car_engine_start_stop' => 'nullable|integer|in:1,2',
            'car_headlamps' => 'nullable|integer|in:1,2',
            'car_power_steering' => 'nullable|integer|in:1,2',

            // Bike-specific
            'bike_headlight_type' => 'nullable|integer|in:1,2',
            'bike_odometer' => 'nullable|integer|in:1,2',
            'bike_drl' => 'nullable|integer|in:1,2',
            'bike_mobile_connectivity' => 'nullable|integer|in:1,2',
            'bike_gps_navigation' => 'nullable|integer|in:1,2',
            'bike_usb_charging_port' => 'nullable|integer|in:1,2',
            'bike_low_battery_indicator' => 'nullable|integer|in:1,2',
            'bike_under_seat_storage' => 'nullable|integer|in:1,2',
            'bike_speedometer' => 'nullable|integer|in:1,2',
            'bike_stand_alarm' => 'nullable|integer|in:1,2',
            'bike_low_fuel_indicator' => 'nullable|integer|in:1,2',
            'bike_low_oil_indicator' => 'nullable|integer|in:1,2',
            'bike_start_type' => 'nullable|integer|in:1,2,3',
            'bike_kill_switch' => 'nullable|integer|in:1,2',
            'bike_break_light' => 'nullable|integer|in:1,2',
            'bike_turn_signal_indicator' => 'nullable|integer|in:1,2',
        ];
    }
}
